# Generated by Django 3.0.5 on 2020-05-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dkraje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dch1', models.BigIntegerField()),
                ('dch2', models.BigIntegerField()),
                ('dch3', models.BigIntegerField()),
                ('dch4', models.BigIntegerField()),
                ('dch5', models.BigIntegerField()),
                ('dch6', models.BigIntegerField()),
                ('dch7', models.BigIntegerField()),
                ('dch8', models.BigIntegerField()),
                ('dch9', models.BigIntegerField()),
                ('dch10', models.BigIntegerField()),
                ('dch11', models.BigIntegerField()),
                ('dch12', models.BigIntegerField()),
                ('dch13', models.BigIntegerField()),
                ('dch14', models.BigIntegerField()),
            ],
            options={
                'db_table': 'dkraje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Iautorsky',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.TextField()),
                ('vyzkum', models.BooleanField()),
                ('teren', models.BooleanField()),
                ('technicky', models.BooleanField()),
                ('kreslil', models.BooleanField()),
                ('fotografoval', models.BooleanField()),
                ('cislo_nove', models.TextField()),
            ],
            options={
                'db_table': 'iautorsky',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Iautorsky2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.TextField()),
                ('kraj', models.TextField()),
                ('okres', models.TextField()),
                ('lokalita', models.TextField()),
                ('cp', models.TextField()),
            ],
            options={
                'db_table': 'iautorsky2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ijmeno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.TextField()),
            ],
            options={
                'db_table': 'ijmeno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ikraj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kraj', models.TextField()),
            ],
            options={
                'db_table': 'ikraj',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ilokalita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lokalita', models.TextField()),
            ],
            options={
                'db_table': 'ilokalita',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Imistni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lok', models.TextField()),
                ('kraj', models.TextField()),
                ('okres', models.TextField()),
                ('lokalita', models.TextField()),
                ('cp', models.TextField()),
                ('cislo_nove', models.TextField()),
                ('cislo_stare', models.TextField()),
            ],
            options={
                'db_table': 'imistni',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Iokres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okres', models.TextField()),
            ],
            options={
                'db_table': 'iokres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Itrid1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popis1', models.TextField()),
            ],
            options={
                'db_table': 'itrid1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Itrid2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popis2', models.TextField()),
            ],
            options={
                'db_table': 'itrid2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Itrid3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popis3', models.TextField()),
            ],
            options={
                'db_table': 'itrid3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Itrid4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popis4', models.TextField()),
            ],
            options={
                'db_table': 'itrid4',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Itrid5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popis5', models.TextField()),
            ],
            options={
                'db_table': 'itrid5',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NsfoxkamPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_cis_stare', models.TextField()),
                ('inv_cis_nove', models.TextField()),
                ('lokalita', models.TextField()),
                ('cp', models.TextField()),
                ('kraj', models.TextField()),
                ('okres', models.TextField()),
                ('tridici1kat', models.TextField()),
                ('tridici2kat', models.TextField()),
                ('tridici3kat', models.TextField()),
                ('tridici4kat', models.TextField()),
                ('tridici5kat', models.TextField()),
                ('zamereni', models.TextField()),
                ('vyzkum', models.TextField()),
                ('teren', models.TextField()),
                ('technicky', models.TextField()),
                ('kreslil', models.TextField()),
                ('fotografoval', models.TextField()),
                ('rozsah', models.TextField()),
                ('soubor', models.TextField()),
                ('gps', models.TextField()),
            ],
            options={
                'db_table': 'nsfoxkam_plan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Table16',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_1', models.CharField(blank=True, db_column='COL 1', max_length=6, null=True)),
                ('col_2', models.IntegerField(blank=True, db_column='COL 2', null=True)),
                ('col_3', models.CharField(blank=True, db_column='COL 3', max_length=26, null=True)),
                ('col_4', models.CharField(blank=True, db_column='COL 4', max_length=2, null=True)),
                ('col_5', models.CharField(blank=True, db_column='COL 5', max_length=14, null=True)),
                ('col_6', models.CharField(blank=True, db_column='COL 6', max_length=15, null=True)),
                ('col_7', models.CharField(blank=True, db_column='COL 7', max_length=12, null=True)),
                ('col_8', models.CharField(blank=True, db_column='COL 8', max_length=27, null=True)),
                ('col_9', models.CharField(blank=True, db_column='COL 9', max_length=12, null=True)),
                ('col_10', models.CharField(blank=True, db_column='COL 10', max_length=13, null=True)),
                ('col_11', models.CharField(blank=True, db_column='COL 11', max_length=6, null=True)),
                ('col_12', models.CharField(blank=True, db_column='COL 12', max_length=54, null=True)),
                ('col_13', models.CharField(blank=True, db_column='COL 13', max_length=23, null=True)),
                ('col_14', models.CharField(blank=True, db_column='COL 14', max_length=23, null=True)),
                ('col_15', models.CharField(blank=True, db_column='COL 15', max_length=23, null=True)),
                ('col_16', models.CharField(blank=True, db_column='COL 16', max_length=23, null=True)),
                ('col_17', models.CharField(blank=True, db_column='COL 17', max_length=23, null=True)),
                ('col_18', models.CharField(blank=True, db_column='COL 18', max_length=91, null=True)),
                ('col_19', models.CharField(blank=True, db_column='COL 19', max_length=17, null=True)),
                ('col_20', models.CharField(blank=True, db_column='COL 20', max_length=29, null=True)),
            ],
            options={
                'db_table': 'table 16',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zzz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zb', models.DecimalField(decimal_places=65535, max_digits=65535)),
            ],
            options={
                'db_table': 'zzz',
                'managed': False,
            },
        ),
    ]
